import numbers
from abc import ABC, abstractmethod
from decimal import Decimal
from fractions import Fraction
from typing import NoReturn, TypeVar

import numpy as np

__all__ = ['Linear', 'LinearType']

T = TypeVar("T", int, float, Decimal, Fraction, np.ndarray)


class Linear(ABC):
    '''Linear defines the operations following linear algebra.
    '''
    __slots__ = ()
    @abstractmethod
    def __abs__(self) -> NoReturn: ...
    @abstractmethod
    def __eq__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __ne__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __gt__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __lt__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __ge__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __le__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __add__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __sub__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __mul__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __truediv__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __pow__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __iadd__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __isub__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __imul__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __itruediv__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __ipow__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __radd__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __rsub__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __rmul__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __rtruediv__(self, other: T | Linear) -> NoReturn: ...
    @abstractmethod
    def __rpow__(self, other: T | Linear) -> NoReturn: ...


LinearType = TypeVar('LinearType', int, float, Fraction,
                     Decimal, np.ndarray, Linear)
